### ISSUE TITLE
Sunnyboy 2.5 not supported?

### ISSUE THREAD

**Issue by arietjens** [ricott/sma.modbus#12]
Hi there!
I’m having a SMA Tripower 5000 and recentst added a SMA Sunnyboy 2.5 inverter.
The 5000 is correcly detecties btw the SMA Homey app. The 2.5 van nog be found.
Is there an issue with the 2.5 or isn’t it possible to use two inverters in the App?
Hope to hear!
Kind regards,
Adri

**Comment by MartinSha** [comment]
I have the same issue. My Tripower 4.0 was found and works well in the app, but when I try to add a Sunny Boy 2.0 the app once only flashed a popup to fill in an ip address but when i had discovered that, the popup had disappeared and refuses to cime back. Result no device found. The modbus is 502 as required and both inverters display correctly in Sunny Explorer etc.

**Comment by ricott** [comment]
Hi,

These are inverters, not linked with a battery? You are using the `Inverter` device type in Homey?
If the answer to the above is yes, then it should be supported, and we need to find out what is not working.

**Comment by MartinSha** [comment]
Hallo,This problem has now been resolved, thank you. I had to uninstall the app and the first inverter device, and reboot Homey, then reinstall the app. Both inverters could then be found. However, I have feeling that the parameters in the new inverter were partly to blame. At the same time these were adjusted by my installer.I have since discovered another strange thing. If the power to one inverter is turned off and on briefly, then the values in the sma app for that device remain frozen, even after restarting the app. The values for my other inverter continued as usual; only the inverter that had had to be turned off and on froze. I had to uninstall the device and install it again to get it to work. I am now searching for a way to add up both daily yield values to use the combined value in a flow, but I am not expert enough to know how...RegardsMartinSent from my Huawei phone-------- Original message --------From: ricott ***@***.***>Date: Sun, 7 Nov 2021, 15:56To: "ricott/sma.modbus" ***@***.***>Cc: MartinSha ***@***.***>, Comment ***@***.***>Subject: Re: [ricott/sma.modbus] Sunnyboy 2.5 not supported? (#12)
Hi,
These are inverters, not linked with a battery? You are using the Inverter device type in Homey?
If the answer to the above is yes, then it should be supported, and we need to find out what is not working.
